/** Où corriger chaque contrôle de vitrine, dans le tableau de bord. */
export const SHOWCASE_ACTIONS: Record<string, { to: string; cta: string }> = {
  bio_length: { to: "/dashboard/profil", cta: "Compléter ma biographie" },
  short_bio: { to: "/dashboard/profil", cta: "Écrire mon accroche" },
  meta: { to: "/dashboard/profil", cta: "Renseigner titre et description SEO" },
  specialties: { to: "/dashboard/profil", cta: "Ajouter mes spécialités" },
  geo: { to: "/dashboard/profil", cta: "Compléter mon adresse" },
  languages: { to: "/dashboard/profil", cta: "Déclarer mes langues" },
  photo: { to: "/dashboard/profil", cta: "Ajouter ma photo" },
  credentials: { to: "/dashboard/profil", cta: "Déposer une certification" },
  price: { to: "/dashboard/profil", cta: "Indiquer mon tarif" },
  modes: { to: "/dashboard/profil", cta: "Choisir mes modes de consultation" },
  availability: { to: "/dashboard/agenda", cta: "Publier mes disponibilités" },
  booking_note: { to: "/dashboard/profil", cta: "Écrire mon message d'accueil" },
  reviews: { to: "/dashboard/avis", cta: "Inviter mes clients à témoigner" },
  gallery: { to: "/dashboard/profil", cta: "Ajouter des photos du cabinet" },
  verified: { to: "/dashboard/profil", cta: "Compléter mon profil pour la vérification" },
  identity: { to: "/dashboard/profil", cta: "Compléter nom et titre" },
  pro_badge: { to: "/dashboard/abonnement", cta: "Découvrir l'offre Pro" },
  ide_verified: { to: "/dashboard/profil", cta: "Renseigner mon identifiant professionnel" },
  training: { to: "/dashboard/profil", cta: "Ajouter ma formation" },
  services: { to: "/dashboard/forfaits", cta: "Décrire mes prestations" },
  durations: { to: "/dashboard/forfaits", cta: "Indiquer les durées" },
  contact: { to: "/dashboard/profil", cta: "Ajouter un moyen de contact" },
  city: { to: "/dashboard/profil", cta: "Renseigner ma ville" },
  canton: { to: "/dashboard/profil", cta: "Renseigner mon canton" },
  address: { to: "/dashboard/profil", cta: "Ajouter mon adresse ou ma zone" },
  geo_consistency: { to: "/dashboard/profil", cta: "Vérifier mes informations géographiques" },
  google_business: { to: "/dashboard/profil", cta: "Relier ma fiche Google" },
  canton_language: { to: "/dashboard/profil", cta: "Ajouter la langue de mon canton" },
  localized_version: { to: "/dashboard/profil", cta: "Ajouter une seconde langue" },
  meta_title: { to: "/dashboard/profil", cta: "Rédiger mon title SEO" },
  meta_description: { to: "/dashboard/profil", cta: "Rédiger ma meta description" },
  h1: { to: "/dashboard/profil", cta: "Compléter mon identité" },
  structured_data: { to: "/dashboard/profil", cta: "Compléter les champs balisés" },
  alt_text: { to: "/dashboard/profil", cta: "Compléter photo et ville" },
  indexable: { to: "/dashboard/profil", cta: "Publier ma fiche" },
  faq: { to: "/dashboard/profil", cta: "Rédiger mes questions fréquentes" },
  articles: { to: "/dashboard/articles", cta: "Publier un article" },
  author: { to: "/dashboard/profil", cta: "Compléter mon profil d'auteur" },
  method_explained: { to: "/dashboard/profil", cta: "Détailler ma méthode" },
  profile_fresh: { to: "/dashboard/profil", cta: "Mettre à jour mon profil" },
  price_fresh: { to: "/dashboard/profil", cta: "Actualiser mes tarifs" },
  availability_fresh: { to: "/dashboard/agenda", cta: "Actualiser mes disponibilités" },
  certifications_valid: { to: "/dashboard/profil", cta: "Mettre à jour mes certifications" },
};

export const SHOWCASE_STATUS_LABEL: Record<string, { label: string; message: string }> = {
  a_renforcer: {
    label: "À renforcer",
    message: "Votre vitrine manque encore d'éléments essentiels pour être bien comprise et rassurante.",
  },
  en_bonne_voie: {
    label: "En bonne voie",
    message: "Les bases sont posées : quelques ajouts feront une vraie différence.",
  },
  solide: {
    label: "Solide",
    message: "Vous êtes proche d'un profil très complet.",
  },
  excellent: {
    label: "Excellent",
    message: "Votre vitrine est complète : pensez à la tenir à jour.",
  },
};
