// Généré depuis les SKILL.md — ne pas éditer à la main.
// Régénérer : node scripts/build-marketing-registry.mjs

export interface MarketingSkill {
  name: string;
  /** Sert au routage : décrit quand mobiliser cette compétence. */
  description: string;
  /** 'holiswiss' = réécrite pour le contexte suisse ; 'upstream' = expertise générique. */
  source: 'holiswiss' | 'upstream';
}

export const MARKETING_SKILLS: MarketingSkill[] = [
  { name: 'ai-seo', source: 'holiswiss', description: 'GEO — être cité par ChatGPT, Perplexity, Gemini et Claude. Format question/réponse citable, requêtes remboursement et géolocalisées, mesure de citabilité. Mots-clés : IA, ChatGPT, Perplexity, citation, GEO, visibilité IA, être cité.' },
  { name: 'cold-email', source: 'holiswiss', description: 'Prospection à froid de thérapeutes suisses : cadre légal LCD, objets, structure, relances, adaptation DE-CH. Mots-clés : prospection, email à froid, démarchage, recruter des thérapeutes, message de contact.' },
  { name: 'content-strategy', source: 'holiswiss', description: 'Stratégie éditoriale Holiswiss : quels articles de blog écrire, pour quelle audience (patient) et dans quelle langue. Familles d\'articles, anti-doublon, déséquilibre FR/DE. Mots-clés : sujet d\'article, ligne éditoriale, calendrier de contenu, quoi écrire, blog.' },
  { name: 'copywriting', source: 'holiswiss', description: 'Rédaction des pages du site (accueil, devenir-thérapeute, tarifs, fiches). Vocabulaire conforme au cadre suisse, ton, adaptation 4 langues. Mots-clés : texte, page, accroche, titre, réécrire, landing, wording.' },
  { name: 'emails', source: 'holiswiss', description: 'Séquences email du cycle de vie thérapeute : activation J0-J14, réactivation, passage à l\'abonnement, avis. Via Resend. Mots-clés : email, séquence, relance, onboarding, newsletter, automatisation email.' },
  { name: 'offers', source: 'holiswiss', description: 'Offre et tarification de l\'abonnement thérapeute : quand monétiser, structure des formules, repères de prix suisses, ce qui doit rester gratuit. Mots-clés : prix, tarif, abonnement, formule, monétisation, combien facturer, premium.' },
  { name: 'programmatic-seo', source: 'holiswiss', description: 'Pages canton × spécialité générées à grande échelle pour l\'annuaire. Taxonomie préalable des spécialités, seuils anti-contenu-mince, hiérarchie d\'URL, 4 langues. Mots-clés : pages canton, pages ville, spécialité, SEO local, pages à grande échelle, maillage.' },
  { name: 'prospecting', source: 'holiswiss', description: 'Constituer une liste qualifiée de thérapeutes suisses : priorité par canton, sources (ASCA, RME, associations), critères de qualification, hygiène de liste. Mots-clés : trouver des thérapeutes, liste, leads, ciblage, quels cantons.' },
  { name: 'referrals', source: 'holiswiss', description: 'Parrainage et bouche-à-oreille entre thérapeutes suisses : prérequis, moment opportun, contreparties non financières, cabinets collectifs et associations. Mots-clés : parrainage, recommandation, bouche-à-oreille, ambassadeur.' },
  { name: 'schema', source: 'holiswiss', description: 'Données structurées JSON-LD : fiches praticiens (Person), pages canton (ItemList + FAQPage), articles. Cohérence balisage/affichage, rendu SSR. Mots-clés : schema, JSON-LD, données structurées, rich snippets, balisage.' },
  { name: 'seo-audit', source: 'holiswiss', description: 'Audit SEO du site : rendu pour les crawlers (React/SSR), indexation, hreflang 4 langues, contenu mince, performance, allégations thérapeutiques. Mots-clés : audit, SEO technique, indexation, Google, hreflang, pourquoi pas de trafic.' },
  { name: 'social', source: 'holiswiss', description: 'Publications réseaux sociaux Holiswiss (Instagram, LinkedIn, TikTok) pour RECRUTER des thérapeutes suisses. Captions en 4 langues FR/DE-CH/IT/EN, 4 piliers éditoriaux, hashtags, brief visuel, carrousels et reels. Mots-clés : post, publication, caption, carrousel, reel, story, hashtag, calendrier éditorial, quoi publier.' },
  { name: 'ab-testing', source: 'upstream', description: 'When the user wants to plan, design, or implement an A/B test or experiment, or build a growth experimentation program. Also use when the user mentions "A/B test," "split test," "experiment," "test this change," "variant copy," "multivariate test," "hypothesis," "should I test this," "which version is better," "test two versions," "statistical significance," "how long should I run this test," "growth experiments," "experiment velocity," "experiment backlog," "ICE score," "experimentation program," or "experiment playbook." Use this whenever someone is comparing two approaches and wants to measure which performs better, or when they want to build a systematic experimentation practice. For tracking implementation, see analytics. For page-level conversion optimization, see cro.' },
  { name: 'ad-creative', source: 'upstream', description: 'When the user wants to generate, iterate, or scale ad creative — headlines, descriptions, primary text, or full ad variations — for any paid advertising platform. Also use when the user mentions \'ad copy variations,\' \'ad creative,\' \'generate headlines,\' \'RSA headlines,\' \'bulk ad copy,\' \'ad iterations,\' \'creative testing,\' \'ad performance optimization,\' \'write me some ads,\' \'Facebook ad copy,\' \'Google ad headlines,\' \'LinkedIn ad text,\' \'static ads,\' \'static ad concepts,\' \'ad templates,\' \'iMessage ad,\' \'chat reveal ad,\' \'fake DM ad,\' \'ChatGPT ad,\' \'Apple Notes ad,\' \'AirDrop ad,\' \'creative strategy,\' \'creative roadmap,\' \'creative retro,\' \'hook writing,\' \'creative review page,\' \'present ad creative for approval,\' \'motion video ad,\' \'faceless video ad,\' \'animated explainer ad,\' \'motion collage ad,\' or \'I need more ad variations.\' Use this whenever someone needs to produce ad copy at scale or iterate on existing ads. For campaign strategy and targeting, see ads. For landing page copy, see copywriting.' },
  { name: 'ads', source: 'upstream', description: 'When the user wants help with paid advertising campaigns on Google Ads, Meta (Facebook/Instagram), LinkedIn, Twitter/X, or other ad platforms. Also use when the user mentions \'PPC,\' \'paid media,\' \'ROAS,\' \'CPA,\' \'ad campaign,\' \'retargeting,\' \'audience targeting,\' \'Google Ads,\' \'Facebook ads,\' \'LinkedIn ads,\' \'ad budget,\' \'cost per click,\' \'ad spend,\' \'should I run ads,\' \'ABM,\' \'account-based marketing,\' \'B2B ads,\' \'lead quality,\' \'negative keywords,\' \'Performance Max,\' \'thought leader ads,\' or \'when should I kill an ad.\' Use this for campaign strategy, audience targeting, bidding, and optimization. For bulk ad creative generation and iteration, see ad-creative. For landing page optimization, see cro.' },
  { name: 'analytics', source: 'upstream', description: 'When the user wants to set up, improve, or audit analytics tracking and measurement. Also use when the user mentions "set up tracking," "GA4," "Google Analytics," "conversion tracking," "event tracking," "UTM parameters," "tag manager," "GTM," "analytics implementation," "tracking plan," "how do I measure this," "track conversions," "attribution," "Mixpanel," "Segment," "are my events firing," or "analytics isn\'t working." Use this whenever someone asks how to know if something is working or wants to measure marketing results. For A/B test measurement, see ab-testing.' },
  { name: 'churn-prevention', source: 'upstream', description: 'When the user wants to reduce churn, build cancellation flows, set up save offers, recover failed payments, or implement retention strategies. Also use when the user mentions \'churn,\' \'cancel flow,\' \'offboarding,\' \'save offer,\' \'dunning,\' \'failed payment recovery,\' \'win-back,\' \'retention,\' \'exit survey,\' \'pause subscription,\' \'involuntary churn,\' \'people keep canceling,\' \'churn rate is too high,\' \'how do I keep users,\' or \'customers are leaving.\' Use this whenever someone is losing subscribers or wants to build systems to prevent it. For post-cancel win-back email sequences, see emails. For in-app upgrade paywalls, see paywalls.' },
  { name: 'co-marketing', source: 'upstream', description: 'When the user wants to find co-marketing partners, plan joint campaigns, or brainstorm partnership opportunities. Use when the user says \'co-marketing,\' \'partner marketing,\' \'joint campaign,\' \'who should we partner with,\' \'integration marketing,\' \'cross-promotion,\' \'collaborate with another company,\' \'partnership ideas,\' or \'co-brand.\' For customer referral programs, see referrals. For launch-specific partnerships, see launch.' },
  { name: 'community-marketing', source: 'upstream', description: 'Build and leverage online communities to drive product growth and brand loyalty. Use when the user wants to create a community strategy, grow a Discord or Slack community, manage a forum or subreddit, build brand advocates, increase word-of-mouth, drive community-led growth, engage users post-signup, or turn customers into evangelists. Trigger phrases: \\"build a community,\\" \\"community strategy,\\" \\"Discord community,\\" \\"Slack community,\\" \\"community-led growth,\\" \\"brand advocates,\\" \\"user community,\\" \\"forum strategy,\\" \\"community engagement,\\" \\"grow our community,\\" \\"ambassador program,\\" \\"community flywheel.\\' },
  { name: 'competitor-profiling', source: 'upstream', description: 'When the user wants to research, profile, or analyze competitors from their URLs. Also use when the user mentions \'competitor profile,\' \'competitor research,\' \'competitor analysis,\' \'profile this competitor,\' \'analyze competitor,\' \'competitive intelligence,\' \'competitor deep dive,\' \'who are my competitors,\' \'competitor landscape,\' \'competitor dossier,\' \'competitive audit,\' or \'research these competitors.\' Input is a list of competitor URLs. Output is structured competitor profile markdown files. For creating comparison/alternative pages from profiles, see competitors. For sales-specific battle cards, see sales-enablement.' },
  { name: 'competitors', source: 'upstream', description: 'When the user wants to create competitor comparison or alternative pages for SEO and sales enablement. Also use when the user mentions \'alternative page,\' \'vs page,\' \'competitor comparison,\' \'comparison page,\' \'[Product] vs [Product],\' \'[Product] alternative,\' \'competitive landing pages,\' \'how do we compare to X,\' \'battle card,\' or \'competitor teardown.\' Use this for any content that positions your product against competitors. Covers four formats: singular alternative, plural alternatives, you vs competitor, and competitor vs competitor. For sales-specific competitor docs, see sales-enablement.' },
  { name: 'copy-editing', source: 'upstream', description: 'When the user wants to edit, review, or improve existing marketing copy, or refresh outdated content. Also use when the user mentions \'edit this copy,\' \'review my copy,\' \'copy feedback,\' \'proofread,\' \'polish this,\' \'make this better,\' \'copy sweep,\' \'tighten this up,\' \'this reads awkwardly,\' \'clean up this text,\' \'too wordy,\' \'sharpen the messaging,\' \'refresh this content,\' \'update this page,\' \'this content is outdated,\' or \'content audit.\' Use this when the user already has copy and wants it improved or refreshed rather than rewritten from scratch. For writing new copy, see copywriting.' },
  { name: 'cro', source: 'upstream', description: 'When the user wants to optimize, improve, or increase conversions on any marketing page or form — including homepage, landing pages, pricing pages, feature pages, lead capture forms, or contact forms. Also use when the user says \'CRO,\' \'conversion rate optimization,\' \'this page isn\'t converting,\' \'improve conversions,\' \'why isn\'t this page working,\' \'my landing page sucks,\' \'form abandonment,\' \'nobody\'s converting,\' \'low conversion rate,\' or \'this page needs work.\' Use this even if the user just shares a URL and asks for feedback. For signup/registration flows, see signup. For post-signup activation, see onboarding. For popups/modals, see popups.' },
  { name: 'customer-research', source: 'upstream', description: 'When the user wants to conduct, analyze, or synthesize customer research. Use when the user mentions "customer research," "ICP research," "talk to customers," "analyze transcripts," "customer interviews," "survey analysis," "support ticket analysis," "voice of customer," "VOC," "build personas," "customer personas," "jobs to be done," "JTBD," "what do customers say," "what are customers struggling with," "Reddit mining," "G2 reviews," "review mining," "digital watering holes," "community research," "forum research," "competitor reviews," "customer sentiment," or "find out why customers churn/convert/buy." Use for both analyzing existing research assets AND gathering new research from online sources. For writing copy informed by research, see copywriting. For acting on research to improve pages, see cro.' },
  { name: 'directory-submissions', source: 'upstream', description: 'When the user wants to submit their product to startup, SaaS, AI, agent, MCP, no-code, or review directories for backlinks, domain rating, and discovery. Also use when the user mentions "directory submissions," "submit to directories," "backlinks from directories," "list my product," "submit to Product Hunt," "BetaList," "TAAFT," "Futurepedia," "G2 listing," "Capterra listing," "AlternativeTo," "SaaSHub," "AI directories," "MCP registry," "agent directory," "dofollow backlinks," "launch directories," or "directory tracker." Use this whenever someone is planning the directory layer of a product launch or an ongoing backlink campaign. For the broader launch moment, see launch. For programmatic SEO pages that should live behind these backlinks, see programmatic-seo. For AI citation optimization, see ai-seo.' },
  { name: 'free-tools', source: 'upstream', description: 'When the user wants to plan, evaluate, or build a free tool for marketing purposes — lead generation, SEO value, or brand awareness. Also use when the user mentions "engineering as marketing," "free tool," "marketing tool," "calculator," "generator," "interactive tool," "lead gen tool," "build a tool for leads," "free resource," "ROI calculator," "grader tool," "audit tool," "should I build a free tool," or "tools for lead gen." Use this whenever someone wants to build something useful and give it away to attract leads or earn links. For downloadable content lead magnets (ebooks, checklists, templates), see lead-magnets.' },
  { name: 'image', source: 'upstream', description: 'When the user wants to create, generate, edit, or optimize images for marketing — blog heroes, social graphics, product mockups, profile banners, listing visuals, or brand assets. Also use when the user mentions \'AI image generation,\' \'generate an image,\' \'create a graphic,\' \'product mockup,\' \'hero image,\' \'social media graphic,\' \'banner image,\' \'cover photo,\' \'profile banner,\' \'listing screenshot,\' \'Flux,\' \'Flux Kontext,\' \'Midjourney,\' \'DALL-E,\' \'GPT Image,\' \'ChatGPT Images,\' \'Ideogram,\' \'Gemini image,\' \'Nano Banana,\' \'Recraft,\' \'Stable Diffusion,\' \'Canva,\' \'Figma,\' \'image optimization,\' \'compress images,\' \'WebP,\' or \'OG image.\' Use this for general-purpose marketing image creation and optimization. For paid ad image creative and platform-specific ad specs, see ad-creative. For video production, see video.' },
  { name: 'influencer-marketing', source: 'upstream', description: 'When the user wants to run influencer, creator, or ambassador partnerships to promote their product — finding and vetting partners, structuring deals, briefing creators, disclosure compliance, and measuring ROI. Also use when the user mentions \'influencer marketing,\' \'creator partnerships,\' \'sponsorships,\' \'YouTube sponsorships,\' \'podcast sponsorships,\' \'brand ambassador,\' \'ambassador program,\' \'creator program,\' \'UGC creators,\' \'B2B influencers,\' \'thought leader ads,\' \'gifting,\' \'product seeding,\' \'whitelisting creator content,\' \'how much to pay an influencer,\' or \'FTC disclosure.\' For affiliate/referral payout mechanics, see referrals. For community-led advocacy, see community-marketing. For turning creator content into paid ads, see ad-creative.' },
  { name: 'launch', source: 'upstream', description: 'When the user wants to plan a product launch, feature announcement, or release strategy. Also use when the user mentions \'launch,\' \'Product Hunt,\' \'feature release,\' \'announcement,\' \'go-to-market,\' \'beta launch,\' \'early access,\' \'waitlist,\' \'product update,\' \'how do I launch this,\' \'launch checklist,\' \'GTM plan,\' or \'we\'re about to ship.\' Use this whenever someone is preparing to release something publicly. For ongoing marketing after launch, see marketing-ideas. For the offer being launched (bonuses, guarantees, scarcity, naming), see offers.' },
  { name: 'lead-magnets', source: 'upstream', description: 'When the user wants to create, plan, or optimize a lead magnet for email capture or lead generation. Also use when the user mentions "lead magnet," "gated content," "content upgrade," "downloadable," "ebook," "cheat sheet," "checklist," "template download," "opt-in," "freebie," "PDF download," "resource library," "content offer," "email capture content," "Notion template," "spreadsheet template," or "what should I give away for emails." Use this for planning what to create and how to distribute it. For interactive tools as lead magnets, see free-tools. For writing the actual content, see copywriting. For the email sequence after capture, see emails.' },
  { name: 'marketing-council', source: 'upstream', description: 'When the user wants multiple expert perspectives on a marketing question — a simulated board of advisors staffed by legendary marketers (Seth Godin, David Ogilvy, Eugene Schwartz, April Dunford, Rory Sutherland, Alex Hormozi, Byron Sharp, and more). Also use when the user mentions \'marketing council,\' \'board of advisors,\' \'advisory board,\' \'what would Seth Godin say,\' \'what would Ogilvy think,\' \'channel Hormozi,\' \'get multiple perspectives,\' \'debate this,\' \'have the council review,\' \'marketing mentors,\' or asks how a famous marketer would approach their problem. The council gives each advisor\'s take through their documented frameworks, surfaces where they disagree, and synthesizes a recommendation. For executing the winning direction, hand off to positioning, offers, copywriting, ads, or the relevant skill.' },
  { name: 'marketing-ideas', source: 'upstream', description: 'When the user needs marketing ideas, inspiration, or strategies for their SaaS or software product. Also use when the user asks for \'marketing ideas,\' \'growth ideas,\' \'how to market,\' \'marketing strategies,\' \'marketing tactics,\' \'ways to promote,\' \'ideas to grow,\' \'what else can I try,\' \'I don\'t know how to market this,\' \'brainstorm marketing,\' or \'what marketing should I do.\' Use this as a starting point whenever someone is stuck or looking for inspiration on how to grow. For specific channel execution, see the relevant skill (ads, social, emails, etc.).' },
  { name: 'marketing-loops', source: 'upstream', description: 'When the user wants to set up a recurring, self-running marketing workflow — a repeatable loop an AI agent runs on a cadence (weekly, daily, on a trigger) rather than a one-off task. Also use when the user mentions \'marketing loop,\' \'recurring marketing workflow,\' \'automate my marketing,\' \'marketing on autopilot,\' \'weekly marketing review,\' \'ad fatigue check,\' \'content refresh loop,\' \'churn watch,\' \'ranking drop alert,\' \'always-on marketing,\' \'marketing automation workflow,\' or \'run this every week.\' Use this to pick, adapt, and schedule an ongoing marketing loop that orchestrates the other marketing skills. For one-off marketing ideas, see marketing-ideas. For the experimentation loop specifically, see ab-testing.' },
  { name: 'marketing-plan', source: 'upstream', description: 'When the user needs a comprehensive marketing plan for a client, a company they advise, or their own product. Also use when the user mentions "marketing plan," "growth plan," "GTM plan," "go-to-market plan," "AARRR plan," "90-day marketing plan," "12-month marketing roadmap," "fractional CMO plan," or "fCMO plan." Generates an exhaustive 13-section plan structured by AARRR (Acquisition, Activation, Retention, Referral, Revenue), customized to the client\'s current budget, team, and stage, mapped to future funding milestones, cross-referenced with the 139-idea marketing-ideas library and an embedded 17-section current-state audit rubric, with a full marketing operations stack showing which skills and MCP/API integrations execute each part. Outputs a Notion-paste-ready markdown document. For positioning and ICP context before planning, see product-marketing. For stage-specific deep work, see onboarding, signup, emails, referrals, pricing.' },
  { name: 'marketing-psychology', source: 'upstream', description: 'When the user wants to apply psychological principles, mental models, or behavioral science to marketing. Also use when the user mentions \'psychology,\' \'mental models,\' \'cognitive bias,\' \'persuasion,\' \'behavioral science,\' \'why people buy,\' \'decision-making,\' \'consumer behavior,\' \'anchoring,\' \'social proof,\' \'scarcity,\' \'loss aversion,\' \'framing,\' or \'nudge.\' Use this whenever someone wants to understand or leverage how people think and make decisions in a marketing context. For applying psychology to specific pages, see cro; for pricing tactics, see pricing; for copy framing, see copywriting.' },
  { name: 'onboarding', source: 'upstream', description: 'When the user wants to optimize post-signup onboarding, user activation, first-run experience, or time-to-value. Also use when the user mentions "onboarding flow," "activation rate," "user activation," "first-run experience," "empty states," "onboarding checklist," "aha moment," "new user experience," "users aren\'t activating," "nobody completes setup," "low activation rate," "users sign up but don\'t use the product," "time to value," or "first session experience." Use this whenever users are signing up but not sticking around. For signup/registration optimization, see signup. For ongoing email sequences, see emails.' },
  { name: 'paywalls', source: 'upstream', description: 'When the user wants to create or optimize in-app paywalls, upgrade screens, upsell modals, or feature gates. Also use when the user mentions "paywall," "upgrade screen," "upgrade modal," "upsell," "feature gate," "convert free to paid," "freemium conversion," "trial expiration screen," "limit reached screen," "plan upgrade prompt," "in-app pricing," "free users won\'t upgrade," "trial to paid conversion," or "how do I get users to pay." Use this for any in-product moment where you\'re asking users to upgrade. Distinct from public pricing pages (see cro) — this focuses on in-product upgrade moments where the user has already experienced value. For pricing decisions, see pricing.' },
  { name: 'popups', source: 'upstream', description: 'When the user wants to create or optimize popups, modals, overlays, slide-ins, or banners for conversion purposes. Also use when the user mentions "exit intent," "popup conversions," "modal optimization," "lead capture popup," "email popup," "announcement banner," "overlay," "collect emails with a popup," "exit popup," "scroll trigger," "sticky bar," or "notification bar." Use this for any overlay or interrupt-style conversion element. For forms outside of popups, see cro. For general page conversion optimization, see cro.' },
  { name: 'pricing', source: 'upstream', description: 'When the user wants help with pricing decisions, packaging, or monetization strategy. Also use when the user mentions \'pricing,\' \'pricing tiers,\' \'freemium,\' \'free trial,\' \'packaging,\' \'price increase,\' \'value metric,\' \'Van Westendorp,\' \'willingness to pay,\' \'monetization,\' \'how much should I charge,\' \'my pricing is wrong,\' \'pricing page,\' \'annual vs monthly,\' \'per seat pricing,\' or \'should I offer a free plan.\' Use this whenever someone is figuring out what to charge or how to structure their plans. For in-app upgrade screens, see paywalls. For offer construction (bonuses, guarantees, value framing, naming) on services/courses/coaching/high-ticket B2B, see offers.' },
  { name: 'product-marketing', source: 'upstream', description: 'When the user wants to create or update their product marketing context document. Also use when the user mentions \'product context,\' \'marketing context,\' \'set up context,\' \'positioning,\' \'who is my target audience,\' \'describe my product,\' \'ICP,\' \'ideal customer profile,\' or wants to avoid repeating foundational information across marketing tasks. Use this at the start of any new project before using other marketing skills — it creates `.agents/product-marketing.md` that all other skills reference for product, audience, and positioning context.' },
  { name: 'public-relations', source: 'upstream', description: 'When the user wants help with public relations, earned media, press coverage, journalist outreach, or media strategy (not pull requests). Also use when the user mentions \'PR,\' \'public relations,\' \'press,\' \'press release,\' \'press coverage,\' \'media outreach,\' \'pitch a journalist,\' \'get featured,\' \'media list,\' \'media kit,\' \'press kit,\' \'newsjacking,\' \'news hijack,\' \'HARO,\' \'Qwoted,\' \'Featured,\' \'Help A Reporter,\' \'reporter request,\' \'tech press,\' \'TechCrunch,\' \'earned media,\' \'thought leadership placement,\' \'op-ed,\' \'guest article,\' \'press contacts,\' or \'how do I get press.\' Use this for earned media work — finding journalists, pitching stories, newsjacking, and responding to press requests. For startup/SaaS/AI directory submissions, see directory-submissions. For product launches, see launch. For social-media engagement, see social. For cold-email outreach to prospects, see cold-email.' },
  { name: 'sales-enablement', source: 'upstream', description: 'When the user wants to create sales collateral, pitch decks, one-pagers, objection handling docs, or demo scripts. Also use when the user mentions \'sales deck,\' \'pitch deck,\' \'one-pager,\' \'leave-behind,\' \'objection handling,\' \'deal-specific ROI analysis,\' \'demo script,\' \'talk track,\' \'sales playbook,\' \'proposal template,\' \'buyer persona card,\' \'help my sales team,\' \'sales materials,\' or \'what should I give my sales reps.\' Use this for any document or asset that helps a sales team close deals. For competitor comparison pages and battle cards, see competitors. For marketing website copy, see copywriting. For cold outreach emails, see cold-email. For the offer being sold (bonuses, guarantees, pricing structure), see offers.' },
  { name: 'signup', source: 'upstream', description: 'When the user wants to optimize signup, registration, account creation, or trial activation flows. Also use when the user mentions "signup conversions," "registration friction," "signup form optimization," "free trial signup," "reduce signup dropoff," "account creation flow," "people aren\'t signing up," "signup abandonment," "trial conversion rate," "nobody completes registration," "too many steps to sign up," or "simplify our signup." Use this whenever the user has a signup or registration flow that isn\'t performing. For post-signup onboarding, see onboarding. For lead capture forms (not account creation), see cro.' },
  { name: 'site-architecture', source: 'upstream', description: 'When the user wants to plan, map, or restructure their website\'s page hierarchy, navigation, URL structure, or internal linking. Also use when the user mentions "sitemap," "site map," "visual sitemap," "site structure," "page hierarchy," "information architecture," "IA," "navigation design," "URL structure," "breadcrumbs," "internal linking strategy," "website planning," "what pages do I need," "how should I organize my site," or "site navigation." Use this whenever someone is planning what pages a website should have and how they connect. NOT for XML sitemaps (that\'s technical SEO — see seo-audit). For SEO audits, see seo-audit. For structured data, see schema.' },
  { name: 'sms', source: 'upstream', description: 'When the user wants to plan, build, or optimize SMS or MMS marketing — including welcome flows, abandoned cart texts, post-purchase, win-back, promotional sends, or transactional/auth SMS. Also use when the user mentions "SMS marketing," "text message campaigns," "SMS sequence," "SMS automation," "abandoned cart text," "post-purchase SMS," "Klaviyo SMS," "Postscript," "Attentive," "Twilio," "A2P 10DLC," "TCPA," "SMS compliance," "short code," "toll-free SMS," "MMS campaign," "should I do SMS," or "SMS vs email." For email sequences, see emails. For SMS copy framing, see copywriting. For opt-in popups that capture phone numbers, see popups.' },
  { name: 'video', source: 'upstream', description: 'When the user wants to create, generate, or produce video content using AI tools or programmatic frameworks. Also use when the user mentions \'video production,\' \'AI video,\' \'Remotion,\' \'Hyperframes,\' \'HeyGen,\' \'Synthesia,\' \'Veo,\' \'Sora,\' \'Runway,\' \'Kling,\' \'Seedance,\' \'Hailuo,\' \'MiniMax,\' \'Pika,\' \'Hunyuan,\' \'Wan,\' \'video generation,\' \'AI avatar,\' \'talking head video,\' \'programmatic video,\' \'video template,\' \'explainer video,\' \'product demo video,\' \'video pipeline,\' \'copy this edit,\' \'match this video style,\' \'reverse-engineer this video,\' \'edit like this reference,\' or \'make me a video.\' Use this for video creation, generation, and production workflows. For video content strategy and what to post, see social. For paid video ad creative, see ad-creative.' },
];

export const SKILL_NAMES = MARKETING_SKILLS.map((s) => s.name);
