/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangTherapeutesIndexRouteImport } from './routes/$lang.therapeutes.index'
import { Route as LangTarifsIndexRouteImport } from './routes/$lang.tarifs.index'
import { Route as LangInscriptionIndexRouteImport } from './routes/$lang.inscription.index'
import { Route as LangEvenementsIndexRouteImport } from './routes/$lang.evenements.index'
import { Route as LangContactIndexRouteImport } from './routes/$lang.contact.index'
import { Route as LangConnexionIndexRouteImport } from './routes/$lang.connexion.index'
import { Route as LangBlogIndexRouteImport } from './routes/$lang.blog.index'
import { Route as LangTherapeuteSlugRouteImport } from './routes/$lang.therapeute.$slug'
import { Route as LangBlogSlugRouteImport } from './routes/$lang.blog.$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangTherapeutesIndexRoute = LangTherapeutesIndexRouteImport.update({
  id: '/therapeutes/',
  path: '/therapeutes/',
  getParentRoute: () => LangRoute,
} as any)
const LangTarifsIndexRoute = LangTarifsIndexRouteImport.update({
  id: '/tarifs/',
  path: '/tarifs/',
  getParentRoute: () => LangRoute,
} as any)
const LangInscriptionIndexRoute = LangInscriptionIndexRouteImport.update({
  id: '/inscription/',
  path: '/inscription/',
  getParentRoute: () => LangRoute,
} as any)
const LangEvenementsIndexRoute = LangEvenementsIndexRouteImport.update({
  id: '/evenements/',
  path: '/evenements/',
  getParentRoute: () => LangRoute,
} as any)
const LangContactIndexRoute = LangContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => LangRoute,
} as any)
const LangConnexionIndexRoute = LangConnexionIndexRouteImport.update({
  id: '/connexion/',
  path: '/connexion/',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRoute,
} as any)
const LangTherapeuteSlugRoute = LangTherapeuteSlugRouteImport.update({
  id: '/therapeute/$slug',
  path: '/therapeute/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/therapeute/$slug': typeof LangTherapeuteSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/connexion/': typeof LangConnexionIndexRoute
  '/$lang/contact/': typeof LangContactIndexRoute
  '/$lang/evenements/': typeof LangEvenementsIndexRoute
  '/$lang/inscription/': typeof LangInscriptionIndexRoute
  '/$lang/tarifs/': typeof LangTarifsIndexRoute
  '/$lang/therapeutes/': typeof LangTherapeutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/therapeute/$slug': typeof LangTherapeuteSlugRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/connexion': typeof LangConnexionIndexRoute
  '/$lang/contact': typeof LangContactIndexRoute
  '/$lang/evenements': typeof LangEvenementsIndexRoute
  '/$lang/inscription': typeof LangInscriptionIndexRoute
  '/$lang/tarifs': typeof LangTarifsIndexRoute
  '/$lang/therapeutes': typeof LangTherapeutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/therapeute/$slug': typeof LangTherapeuteSlugRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/connexion/': typeof LangConnexionIndexRoute
  '/$lang/contact/': typeof LangContactIndexRoute
  '/$lang/evenements/': typeof LangEvenementsIndexRoute
  '/$lang/inscription/': typeof LangInscriptionIndexRoute
  '/$lang/tarifs/': typeof LangTarifsIndexRoute
  '/$lang/therapeutes/': typeof LangTherapeutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/therapeute/$slug'
    | '/$lang/blog/'
    | '/$lang/connexion/'
    | '/$lang/contact/'
    | '/$lang/evenements/'
    | '/$lang/inscription/'
    | '/$lang/tarifs/'
    | '/$lang/therapeutes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/blog/$slug'
    | '/$lang/therapeute/$slug'
    | '/$lang/blog'
    | '/$lang/connexion'
    | '/$lang/contact'
    | '/$lang/evenements'
    | '/$lang/inscription'
    | '/$lang/tarifs'
    | '/$lang/therapeutes'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/blog/$slug'
    | '/$lang/therapeute/$slug'
    | '/$lang/blog/'
    | '/$lang/connexion/'
    | '/$lang/contact/'
    | '/$lang/evenements/'
    | '/$lang/inscription/'
    | '/$lang/tarifs/'
    | '/$lang/therapeutes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/therapeutes/': {
      id: '/$lang/therapeutes/'
      path: '/therapeutes'
      fullPath: '/$lang/therapeutes/'
      preLoaderRoute: typeof LangTherapeutesIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/tarifs/': {
      id: '/$lang/tarifs/'
      path: '/tarifs'
      fullPath: '/$lang/tarifs/'
      preLoaderRoute: typeof LangTarifsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/inscription/': {
      id: '/$lang/inscription/'
      path: '/inscription'
      fullPath: '/$lang/inscription/'
      preLoaderRoute: typeof LangInscriptionIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/evenements/': {
      id: '/$lang/evenements/'
      path: '/evenements'
      fullPath: '/$lang/evenements/'
      preLoaderRoute: typeof LangEvenementsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact/': {
      id: '/$lang/contact/'
      path: '/contact'
      fullPath: '/$lang/contact/'
      preLoaderRoute: typeof LangContactIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/connexion/': {
      id: '/$lang/connexion/'
      path: '/connexion'
      fullPath: '/$lang/connexion/'
      preLoaderRoute: typeof LangConnexionIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/therapeute/$slug': {
      id: '/$lang/therapeute/$slug'
      path: '/therapeute/$slug'
      fullPath: '/$lang/therapeute/$slug'
      preLoaderRoute: typeof LangTherapeuteSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangTherapeuteSlugRoute: typeof LangTherapeuteSlugRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangConnexionIndexRoute: typeof LangConnexionIndexRoute
  LangContactIndexRoute: typeof LangContactIndexRoute
  LangEvenementsIndexRoute: typeof LangEvenementsIndexRoute
  LangInscriptionIndexRoute: typeof LangInscriptionIndexRoute
  LangTarifsIndexRoute: typeof LangTarifsIndexRoute
  LangTherapeutesIndexRoute: typeof LangTherapeutesIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangTherapeuteSlugRoute: LangTherapeuteSlugRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangConnexionIndexRoute: LangConnexionIndexRoute,
  LangContactIndexRoute: LangContactIndexRoute,
  LangEvenementsIndexRoute: LangEvenementsIndexRoute,
  LangInscriptionIndexRoute: LangInscriptionIndexRoute,
  LangTarifsIndexRoute: LangTarifsIndexRoute,
  LangTherapeutesIndexRoute: LangTherapeutesIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
