
UPDATE specialties SET
  description_de = CASE slug
    WHEN 'accompagnement-psy' THEN 'Psychologische Begleitung und aktives Zuhören in Übergangs- oder schwierigen Momenten.'
    WHEN 'acupuncture' THEN 'Setzen feiner Nadeln an präzisen Punkten, um den Energiefluss wiederherzustellen.'
    WHEN 'aromatherapie' THEN 'Behandlung mit ätherischen Ölen zur Harmonisierung von Körper und Emotionen.'
    WHEN 'art-therapie' THEN 'Einsatz künstlerischer Medien zur Erforschung und Wandlung von Emotionen.'
    WHEN 'ayurveda' THEN 'Traditionelle indische Heilkunst, die auf dem Gleichgewicht der Doshas beruht.'
    WHEN 'breathwork' THEN 'Bewusste Atemtechniken zur Befreiung festgehaltener Emotionen.'
    WHEN 'coaching-de-vie' THEN 'Zielorientierte Begleitung, um Wünsche zu klären und ins Handeln zu kommen.'
    WHEN 'emdr' THEN 'Therapie durch Augenbewegungen, wirksam bei Traumata und posttraumatischem Stress.'
    WHEN 'fleurs-de-bach' THEN 'Blütenessenzen nach Dr. Bach zur Harmonisierung emotionaler Zustände.'
    WHEN 'hypnose' THEN 'Veränderter Bewusstseinszustand zur Lösung von Blockaden, Ängsten und einschränkenden Mustern.'
    WHEN 'lahochi' THEN 'Hochfrequente Energiearbeit durch Handauflegen.'
    WHEN 'lithotherapie' THEN 'Behandlung mit Steinen und Mineralien und deren energetischen Schwingungen.'
    WHEN 'magnetisme' THEN 'Energieübertragung durch Handauflegen zur Linderung von Schmerzen und Blockaden.'
    WHEN 'massage-bien-etre' THEN 'Entspannende Massagen, um Verspannungen zu lösen und Wohlbefinden zu fördern.'
    WHEN 'massotherapie' THEN 'Gezielte therapeutische Massagen bei muskulären und gelenkbezogenen Beschwerden.'
    WHEN 'medecine-chinoise' THEN 'Traditionelle Chinesische Medizin mit Akupunktur, Kräuterheilkunde und Ernährungslehre.'
    WHEN 'meditation' THEN 'Meditative Praktiken zur Förderung innerer Ruhe und Präsenz.'
    WHEN 'micronutrition' THEN 'Ernährungsansatz basierend auf essenziellen Mikronährstoffen für den Organismus.'
    WHEN 'naturopathie' THEN 'Präventive Medizin mit natürlichen Mitteln zur Stärkung der Selbstheilungskräfte.'
    WHEN 'nutrition' THEN 'Individuelle Ernährungsberatung für ein nachhaltiges Gleichgewicht.'
    WHEN 'osteopathie' THEN 'Manuelle Therapie zur Wiederherstellung der Beweglichkeit der Körperstrukturen.'
    WHEN 'phytotherapie' THEN 'Therapeutische Anwendung von Heilpflanzen als Tees, Extrakte oder Tinkturen.'
    WHEN 'psychotherapie' THEN 'Therapeutische Gesprächsbegleitung zur Bewältigung psychischer und emotionaler Herausforderungen.'
    WHEN 'radiesthesie' THEN 'Nutzung des Pendels zur Erkennung von Energien und Ungleichgewichten.'
    WHEN 'reflexologie' THEN 'Stimulation von Reflexzonen an Füssen oder Händen, die den Organen entsprechen.'
    WHEN 'reiki' THEN 'Japanische Energiearbeit durch Handauflegen.'
    WHEN 'relaxation' THEN 'Tiefenentspannungstechniken zum Lösen körperlicher und mentaler Anspannung.'
    WHEN 'shiatsu' THEN 'Japanische Technik manueller Druckpunkte entlang der Energiemeridiane.'
    WHEN 'sonotherapie' THEN 'Klangbehandlung mit Klangschalen, Gongs und Klanginstrumenten.'
    WHEN 'sophrologie' THEN 'Dynamische Entspannungsmethode mit Atmung, Muskelentspannung und positiver Visualisierung.'
    WHEN 'yoga' THEN 'Jahrtausendealte Disziplin aus Körperhaltungen, Atmung und Meditation.'
  END,
  description_it = CASE slug
    WHEN 'accompagnement-psy' THEN 'Sostegno psicologico e ascolto attivo nei momenti di transizione o fragilità.'
    WHEN 'acupuncture' THEN 'Inserimento di aghi sottili in punti precisi per ristabilire la circolazione energetica.'
    WHEN 'aromatherapie' THEN 'Cura con oli essenziali per equilibrare corpo ed emozioni.'
    WHEN 'art-therapie' THEN 'Uso dei mezzi artistici per esplorare e trasformare le emozioni.'
    WHEN 'ayurveda' THEN 'Medicina tradizionale indiana millenaria basata sull''equilibrio dei dosha.'
    WHEN 'breathwork' THEN 'Tecniche di respirazione consapevole per liberare le emozioni.'
    WHEN 'coaching-de-vie' THEN 'Accompagnamento orientato agli obiettivi per chiarire le aspirazioni e agire.'
    WHEN 'emdr' THEN 'Terapia con movimenti oculari efficace per traumi e stress post-traumatico.'
    WHEN 'fleurs-de-bach' THEN 'Elisir floreali del Dr. Bach che agiscono sugli stati emotivi.'
    WHEN 'hypnose' THEN 'Stato modificato di coscienza per sciogliere blocchi, fobie e automatismi limitanti.'
    WHEN 'lahochi' THEN 'Cura energetica ad alta frequenza tramite imposizione delle mani.'
    WHEN 'lithotherapie' THEN 'Cura con pietre e minerali e le loro vibrazioni energetiche.'
    WHEN 'magnetisme' THEN 'Trasmissione di energia con le mani per alleviare dolori e blocchi.'
    WHEN 'massage-bien-etre' THEN 'Massaggi rilassanti per sciogliere le tensioni e favorire il benessere.'
    WHEN 'massotherapie' THEN 'Massaggi terapeutici mirati su problematiche muscolari e articolari.'
    WHEN 'medecine-chinoise' THEN 'Medicina tradizionale cinese: agopuntura, farmacopea e dietetica energetica.'
    WHEN 'meditation' THEN 'Pratiche meditative per coltivare la calma interiore e la presenza.'
    WHEN 'micronutrition' THEN 'Approccio nutrizionale basato sui micronutrienti essenziali per l''organismo.'
    WHEN 'naturopathie' THEN 'Medicina preventiva con mezzi naturali per rafforzare l''autoguarigione.'
    WHEN 'nutrition' THEN 'Accompagnamento nutrizionale personalizzato per un equilibrio alimentare duraturo.'
    WHEN 'osteopathie' THEN 'Terapia manuale che ristabilisce la mobilità delle strutture del corpo.'
    WHEN 'phytotherapie' THEN 'Uso terapeutico delle piante medicinali in tisane, estratti o tinture.'
    WHEN 'psychotherapie' THEN 'Accompagnamento terapeutico verbale per superare difficoltà psicologiche ed emotive.'
    WHEN 'radiesthesie' THEN 'Uso del pendolo per rilevare energie e squilibri.'
    WHEN 'reflexologie' THEN 'Stimolazione di zone riflesse di piedi o mani corrispondenti agli organi.'
    WHEN 'reiki' THEN 'Cura energetica giapponese tramite imposizione delle mani.'
    WHEN 'relaxation' THEN 'Tecniche di rilassamento profondo per allentare tensioni fisiche e mentali.'
    WHEN 'shiatsu' THEN 'Tecnica giapponese di pressioni manuali lungo i meridiani energetici.'
    WHEN 'sonotherapie' THEN 'Cura vibrazionale con campane tibetane, gong e strumenti sonori.'
    WHEN 'sophrologie' THEN 'Metodo di rilassamento dinamico che unisce respirazione, distensione e visualizzazione positiva.'
    WHEN 'yoga' THEN 'Disciplina millenaria che unisce posture, respirazione e meditazione.'
  END,
  description_en = CASE slug
    WHEN 'accompagnement-psy' THEN 'Psychological support and active listening during transitions or fragile moments.'
    WHEN 'acupuncture' THEN 'Insertion of fine needles at specific points to restore energy flow.'
    WHEN 'aromatherapie' THEN 'Treatment with essential oils to balance body and emotions.'
    WHEN 'art-therapie' THEN 'Use of artistic media to explore and transform emotions.'
    WHEN 'ayurveda' THEN 'Ancient traditional Indian medicine based on balancing the doshas.'
    WHEN 'breathwork' THEN 'Conscious breathing techniques to release emotions.'
    WHEN 'coaching-de-vie' THEN 'Goal-oriented support to clarify aspirations and take action.'
    WHEN 'emdr' THEN 'Eye-movement therapy effective for trauma and post-traumatic stress.'
    WHEN 'fleurs-de-bach' THEN 'Dr. Bach''s flower essences acting on emotional states.'
    WHEN 'hypnose' THEN 'Altered state of consciousness used to release blocks, phobias and limiting patterns.'
    WHEN 'lahochi' THEN 'High-frequency energy healing through the laying on of hands.'
    WHEN 'lithotherapie' THEN 'Healing with stones and minerals and their energetic vibrations.'
    WHEN 'magnetisme' THEN 'Transmission of energy through the hands to relieve pain and blockages.'
    WHEN 'massage-bien-etre' THEN 'Relaxing massages to release tension and promote well-being.'
    WHEN 'massotherapie' THEN 'Therapeutic massages targeting muscular and joint issues.'
    WHEN 'medecine-chinoise' THEN 'Traditional Chinese Medicine: acupuncture, herbs and energetic dietetics.'
    WHEN 'meditation' THEN 'Meditative practices to cultivate inner calm and presence.'
    WHEN 'micronutrition' THEN 'Nutritional approach based on essential micronutrients for the body.'
    WHEN 'naturopathie' THEN 'Preventive medicine using natural means to strengthen self-healing.'
    WHEN 'nutrition' THEN 'Personalised nutritional support for lasting dietary balance.'
    WHEN 'osteopathie' THEN 'Manual therapy that restores mobility of body structures.'
    WHEN 'phytotherapie' THEN 'Therapeutic use of medicinal plants as teas, extracts or tinctures.'
    WHEN 'psychotherapie' THEN 'Talk-based therapeutic support to overcome psychological and emotional challenges.'
    WHEN 'radiesthesie' THEN 'Use of the pendulum to detect energies and imbalances.'
    WHEN 'reflexologie' THEN 'Stimulation of reflex zones on feet or hands corresponding to organs.'
    WHEN 'reiki' THEN 'Japanese energy healing through the laying on of hands.'
    WHEN 'relaxation' THEN 'Deep-relaxation techniques to release physical and mental tension.'
    WHEN 'shiatsu' THEN 'Japanese technique of manual pressures along energy meridians.'
    WHEN 'sonotherapie' THEN 'Vibrational treatment with singing bowls, gongs and sound instruments.'
    WHEN 'sophrologie' THEN 'Dynamic relaxation method combining breathing, muscle release and positive visualisation.'
    WHEN 'yoga' THEN 'Ancient discipline combining postures, breathing and meditation.'
  END
WHERE slug IN ('accompagnement-psy','acupuncture','aromatherapie','art-therapie','ayurveda','breathwork','coaching-de-vie','emdr','fleurs-de-bach','hypnose','lahochi','lithotherapie','magnetisme','massage-bien-etre','massotherapie','medecine-chinoise','meditation','micronutrition','naturopathie','nutrition','osteopathie','phytotherapie','psychotherapie','radiesthesie','reflexologie','reiki','relaxation','shiatsu','sonotherapie','sophrologie','yoga');
