-- Import du catalogue officiel Tarif 590 (Médecine complémentaire LCA)
-- Source : fichier officiel « Tarif 590 V6 » fourni par HoliSwiss. Aucune position inventée.

insert into public.tariff_catalogs (name, version, source, valid_from, is_active)
values ('Tarif 590', 'V6', 'Tarif 590 — Médecine complémentaire LCA (fichier officiel V6)', '2016-01-01', true)
on conflict (name, version) do update
  set source = excluded.source,
      valid_from = excluded.valid_from,
      is_active = true;

update public.tariff_catalogs set is_active = false
where not (name = 'Tarif 590' and version = 'V6');

with c as (select id from public.tariff_catalogs where name = 'Tarif 590' and version = 'V6')
insert into public.tariff_positions (catalog_id, code, designation, description, unit, is_active)
select c.id, v.code, v.designation, v.description, v.unit, v.is_active
from c cross join (values
  ('1200', 'Anamnèse / bilan / diagnostic / constatations médicales, par période de 5 min.', 'Numéros tarifaires Généralités — Anamnèse (données personnelles, antécédents médicaux, thérapies ou traitements antérieurs, médicaments, risques, etc.), examens ainsi que diagnostics et résultats indépendants de la Méthode et de la spécialité.', null, true),
  ('1250', 'Consultation manquée', 'Numéros tarifaires Généralités', null, true),
  ('1251', 'Supplément nuit, dimanche et jours fériés', 'Numéros tarifaires Généralités — Supplément forfaitaire pour traitements de nuit (entre 22h00-06h00), ainsi que les dimanches et jours fériés', null, true),
  ('1252', 'Supplément consultation extraordinaire dans des situations aigües', 'Numéros tarifaires Généralités — Supplément forfaitaire pour traitements aigus imprévus. Ne doit pas être combiné avec le chiffre tarifaire 1251.', null, true),
  ('1253', 'Rapport formalisé', 'Numéros tarifaires Généralités — Forfaits pour la réponse à un questionnaire. Comprend en règle générale les réponses à des questions ciblées de l''assureur.', null, true),
  ('1254', 'Rapport non formalisé', 'Numéros tarifaires Généralités — Forfaits pour établissement d''un rapport. La conception des rapports non formalisés est libre.', null, true),
  ('1255', 'Leeches, par pièce', 'Numéros tarifaires Généralités', null, true),
  ('1256', 'Compensation de voyage', 'Numéros tarifaires Généralités — Supplément forfaitaire pour l''indemnité de déplacement pour les visites à domicile', null, true),
  ('1003', 'Acupressure, par période de 5 min.', 'Préstations', null, true),
  ('1004', 'Acupuncture, par période de 5 min.', 'Préstations — Comprend l''électroacupuncture, l''acupuncture au laser, la moxibustion, l''auriculothérapie, acupuncture du crâne, acupuncture oculaire, y compris l''application combinée avec des lampes chauffantes.', null, true),
  ('1005', 'APM thérapie (Thérapie par le massage sur méridiens d''acupuncture), par période de 5 min.', 'Préstations', null, true),
  ('1006', 'Technique Alexander, par période de 5 min.', 'Préstations', null, true),
  ('1007', 'Tui-Na/An-Mo, par période de 5 min.', 'Préstations — Comprend moxibustion, y compris l''application combinée avec des lampes chauffantes.', null, true),
  ('1008', 'Médécine anthroposophique, traitement/consultation, par période de 5 min.', 'Préstations', null, true),
  ('1010', 'Aromathérapie, par période de 5 min.', 'Préstations', null, true),
  ('1011', 'Travail asiatique d’énergie et du corps, par période de 5 min.', 'Préstations', null, true),
  ('1012', 'Thérapie respiratoire, par période de 5 min.', 'Préstations', null, true),
  ('1013', 'Atlaslogie, par période de 5 min.', 'Préstations', null, true),
  ('1014', 'Audio-psycho-phonologie/Tomatis, par période de 5 min.', 'Préstations', null, true),
  ('1016', 'Auro-Soma thérapie, par période de 5 min.', 'Préstations', null, true),
  ('1017', 'Training autogène, par période de 5 min.', 'Préstations — La thérapie par la parole ou la psychothérapie ne fait pas partie du training autogène.', null, true),
  ('1021', 'Massage ayurvédique, par période de 5 min.', 'Préstations — Massage - du corps entier (abhyanga), - de la tête (mukhābhyanga) et - des pieds (padābhyanga), Traitement sur l’entier du corps avec des poudres ou des pâtes/cataplasmes (udvartana, lepa), Massage des points vitaux (Marma/Kalari-Massage), Utilisation de pochons de plantes (patrapottali), Massage avec des pochons de sel ou de sable (lavana/valuka- pindasveda), Massage avec des pochons (pinda-sveda), Massage avec des pochons de riz (sastika-shali-pinda-sveda)', null, true),
  ('1022', 'Thérapie des fleurs de Bach, par période de 5 min.', 'Préstations', null, true),
  ('1024', 'Thérapie par le mouvement (intégrat./cliniq.), par période de 5 min.', 'Préstations', null, true),
  ('1025', 'Massage du tissu conjonctif, par période de 5 min.', 'Préstations', null, true),
  ('1026', 'Biofeedback, par période de 5 min.', 'Préstations', null, true),
  ('1027', 'Biorésonance, par période de 5 min.', 'Préstations', null, true),
  ('1028', 'Biochimie selon Schüssler, par période de 5 min.', 'Préstations', null, true),
  ('1029', 'Psychologie biodynamique/Biodynamique, par période de 5 min.', 'Préstations', null, true),
  ('1030', 'Sangsues, par période de 5 min.', 'Préstations', null, true),
  ('1145', 'Bowtech, par période de 5 min.', 'Préstations', null, true),
  ('1031', 'Brain Gym, par période de 5 min.', 'Préstations', null, true),
  ('1032', 'Hydrothérapie du côlon, par période de 5 min.', 'Préstations', null, true),
  ('1034', 'Thérapie craniosacrale, par période de 5 min.', 'Préstations', null, true),
  ('1035', 'Deep Draining, par période de 5 min.', 'Préstations', null, true),
  ('1036', 'Autohémothérapie/thérapie autosanguine, par période de 5 min.', 'Préstations', null, true),
  ('1146', 'Temps d''action en cas de traitement parallèle, par période de 5 min.', 'Préstations — Période pendant laquelle le thérapeute travaille avec ou sur d''autres patients/clients.', null, true),
  ('1037', 'Électroacupuncture, par période de 5 min.', 'Préstations', null, true),
  ('1038', 'Électroacupuncture selon Voll, par période de 5 min.', 'Préstations', null, true),
  ('1039', 'Électrothérapie, par période de 5 min.', 'Préstations', null, true),
  ('1045', 'Massage ésalien, par période de 5 min.', 'Préstations', null, true),
  ('1047', 'Eutonie Gerda Alexander, par période de 5 min.', 'Préstations', null, true),
  ('1048', 'Chromopuncture, par période de 5 min.', 'Préstations', null, true),
  ('1049', 'Thérapie par la couleur, par période de 5 min.', 'Préstations', null, true),
  ('1050', 'Fasciathérapie, par période de 5 min.', 'Préstations', null, true),
  ('1051', 'Méthode Feldenkrais, par période de 5 min.', 'Préstations', null, true),
  ('1052', 'Massage des zones réflexes du pied, par période de 5 min.', 'Préstations', null, true),
  ('1053', 'Thérapie d’oxydation hématogène, par période de 5 min.', 'Préstations', null, true),
  ('1054', 'Yoga thérapie, par période de 5 min.', 'Préstations', null, true),
  ('1055', 'Eurythmie thérapeutique, par période de 5 min.', 'Préstations', null, true),
  ('1056', 'Hippothérapie, par période de 5 min.', 'Préstations', null, true),
  ('1057', 'Homéopathie, Traitement/Consultation, par période de 5 min.', 'Préstations — Ce code tarifaire comprend toutes les activités spécifiques à une spécialité en contact direct avec le patient (anamnèse homéopathique, y compris la consultation téléphonique), à l''exception de la répertorisation (voir code tarifaire 1127).', null, true),
  ('1058', 'Hydrothérapie, par période de 5 min.', 'Préstations — Comprend jets, lavages, bains, utilisations de l''eau selon Kneipp, balnéologie, cataplasmes, enveloppements, fango', null, true),
  ('1060', 'Kinésiologie, par période de 5 min.', 'Préstations', null, true),
  ('1061', 'Thérapie sonore, par période de 5 min.', 'Préstations', null, true),
  ('1062', 'Massage classique, par période de 5 min.', 'Préstations — Synonymes pour massage classique: massage empirique, thérapeutique, y c. massage du côlon.', null, true),
  ('1063', 'Thérapie selon Kneipp, par période de 5 min.', 'Préstations — Concept total (5 piliers)', null, true),
  ('1065', 'Thérapie par la lumière, par période de 5 min.', 'Préstations', null, true),
  ('1259', 'Liebscher & Bracht, par période de 5 min.', 'Préstations', null, true),
  ('1066', 'Drainage lymphatique, manuel, par période de 5 min.', 'Préstations', null, true),
  ('1067', 'Magnétothérapie/thérapie par champs magnétiques, par période de 5 min.', 'Préstations', null, true),
  ('1068', 'Thérapie par la peinture, par période de 5 min.', 'Préstations', null, true),
  ('1069', 'Mésothérapie, par période de 5 min.', 'Préstations', null, true),
  ('1070', 'Massage métamorphique, par période de 5 min.', 'Préstations', null, true),
  ('1072', 'Musicothérapie, par période de 5 min.', 'Préstations', null, true),
  ('1073', 'Massage des zones réflexes musculaires, par période de 5 min.', 'Préstations', null, true),
  ('1074', 'Thérapie myofonctionelle, par période de 5 min.', 'Préstations', null, true),
  ('1075', 'Thérapie neurale, par période de 5 min.', 'Préstations', null, true),
  ('1080', 'Formation du mouvement rythmo-organique Medau, par période de 5 min.', 'Préstations', null, true),
  ('1081', 'Ortho-Bionomy, par période de 5 min.', 'Préstations', null, true),
  ('1082', 'Thérapie orthomoléculaire, par période de 5 min.', 'Préstations — Comprend la consultation orthomoléculaire, l''exclusion des préparations orthomoléculaires. Ceux-ci sonst facturés sous le numéro tarifaire 1310.', null, true),
  ('1084', 'Thérapie par l’ozone, par période de 5 min.', 'Préstations', null, true),
  ('1085', 'Phytothérapie, par période de 5 min.', 'Préstations — y compris spagyrie; comprend aussi l''évaluation téléphonique', null, true),
  ('1087', 'Polarity, par période de 5 min.', 'Préstations', null, true),
  ('1088', 'Intégration posturale, par période de 5 min.', 'Préstations', null, true),
  ('1089', 'Psychomotricité, par période de 5 min.', 'Préstations', null, true),
  ('1090', 'Massage des zones psychogènes, par période de 5 min.', 'Préstations', null, true),
  ('1091', 'Thérapie de théâtre de marionnettes,  par période de 5 min.', 'Préstations', null, true),
  ('1092', 'Qi Gong, par période de 5 min.', 'Préstations', null, true),
  ('1093', 'Rebalancing, par période de 5 min.', 'Préstations', null, true),
  ('1094', 'Thérapie par nouvelle naissance, par période de 5 min.', 'Préstations', null, true),
  ('1096', 'Reiki, par période de 5 min.', 'Préstations', null, true),
  ('1097', 'Rolfing/intégration structurelle, par période de 5 min.', 'Préstations', null, true),
  ('1098', 'Massages rythmiques anthrop., par période de 5 min.', 'Préstations', null, true),
  ('1099', 'Oxygénotherapie en plusieurs étapes, par période de 5 min.', 'Préstations', null, true),
  ('1100', 'Shiatsu, par période de 5 min.', 'Préstations', null, true),
  ('1101', 'Shin Tai, par période de 5 min.', 'Préstations', null, true),
  ('1102', 'Sophrologie / Sophrologie Caycédienne, par période de 5 min.', 'Préstations', null, true),
  ('1104', 'Thérapie Sumathu, par période de 5 min.', 'Préstations', null, true),
  ('1105', 'Sympathicothérapie, par période de 5 min.', 'Préstations', null, true),
  ('1106', 'Tai Chi, par période de 5 min.', 'Préstations', null, true),
  ('1108', 'Thérapie par la danse, par période de 5 min.', 'Préstations', null, true),
  ('1111', 'Massage thaï, par période de 5 min.', 'Préstations', null, true),
  ('1113', 'Thermographie, par période de 5 min.', 'Préstations', null, true),
  ('1114', 'Médecine tibétaine, traitement/consultation, par période de 5 min.', 'Préstations', null, true),
  ('1115', 'Touch for Health, par période de 5 min.', 'Préstations', null, true),
  ('1117', 'Massage selon Trager, par période de 5 min.', 'Préstations', null, true),
  ('1118', 'Thérapie par du sang irradié (UV), par période de 5 min.', 'Préstations', null, true),
  ('1120', 'Vitalpratique selon Vuille, par période de 5 min.', 'Préstations', null, true),
  ('1121', 'Cataplasmes/enveloppements/fango, par période de 5 min.', 'Préstations', null, true),
  ('1122', 'Équilibration vertébrale, par période de 5 min.', 'Préstations', null, true),
  ('1123', 'Zilgrei, par période de 5 min.', 'Préstations', null, true),
  ('1127', 'Homéopathie - Répertorisation, par période de 5 min.', 'Préstations — La répertorisation, indépendamment de la présence ou de l''absence du patient, est facturée sous ce code tarifaire.', null, true),
  ('1128', 'Thérapie Adveda-Eugemed, par période de 5 min.', 'Préstations', null, true),
  ('1131', 'Thérapie à médiation plastique, par période de 5 min.', 'Préstations', null, true),
  ('1132', 'Thérapie intermédiale, par période de 5 min.', 'Préstations', null, true),
  ('1133', 'Thérapie des méridiens, par période de 5 min.', 'Préstations', null, true),
  ('1134', 'Réflexothérapie, par période de 5 min.', 'Préstations — Comprend le massage des zones réflexes du corps, des muscles et des microsystèmes comme les oreilles, les mains et les pieds.', null, true),
  ('1141', 'Thérapie Dorn/Breuss,  par période de 5 min.', 'Préstations', null, true),
  ('1143', 'Thérapie Cantharide, par période de 5 min.', 'Préstations', null, true),
  ('1144', 'Thérapie du développement et de l''apprentissage selon PäPKi, par période de 5 min.', 'Préstations', null, true),
  ('1201', 'Thérapie par le drame, par période de 5 min.', 'Préstations', null, true),
  ('1202', 'Art de parole thérapeutique, par période de 5 min.', 'Préstations', null, true),
  ('1203', 'Ostéopathie, par période de 5 min.', 'Préstations', null, true),
  ('1204', 'Etiopathie, par période de 5 min.', 'Préstations', null, true),
  ('1205', 'Méthodes de détoxication, par période de 5 min.', 'Préstations — Comprend les ventouses, Thérapie par les sangsues, la Méthode Baunscheidt, le Gua Sha, purger, méthode Röder, saignée, Vomissement thérapeutique (vamana), Purgation (virecana), Irrigation colonique (niruha basti, matra basti), Saignée (rakta-mokshana), Rinçage nasal (nasya), Traitement oculaire (akshi/netra tarpana), Traitement auriculaire (karna purana), Cautérisation (agni karma)', null, true),
  ('1206', 'Thérapie nutritionnelle, par période de 5 min.', 'Préstations', null, true),
  ('1209', 'Jets ayurvédique, par période de 5 min.', 'Préstations — Comprend les Jets d’huile sur le corps entier (kaya seka, pizhichil), Coulées sur le front (shirodhara), Application locale + rétention intensive d’huile sur la tête (shiro basti), colonne vertébrale (kati-, prishta, griva-basti), genoux (janu basti)', null, true),
  ('1210', 'Spiraldynamik,  par période de 5 min.', 'Préstations', null, true),
  ('1214', 'Orthonomie fonctionnelle et intégration, par période de 5 min.', 'Préstations', null, true),
  ('1218', 'Thérapie Lomilomi, par période de 5 min.', 'Préstations', null, true),
  ('1219', 'Hyperthermie, par période de 5 min.', 'Préstations — pour médecins et cliniques', null, true),
  ('1220', 'Thérapie Boeger, par période de 5 min.', 'Préstations', null, true),
  ('1222', 'Thérapie du sport et en activité physique adaptée, par période de 5 min.', 'Préstations', null, true),
  ('1223', 'Premiers Secours Emotionnels, par période de 5 min.', 'Préstations', null, true),
  ('1310', 'Remèdes médecine complémentaire', 'Remède — Tous les médicaments de médecine complémentaire sont enrigistrés selon à la règle suivante:
«nom du produit resp. utilisation, fabricant, quantité (p. ex. taille de l''emballage) et forme posologique»
Exemple: «UMCKALOABO Solution, Schwabe, 50 ml» resp. «Phytothérapeutiques toux, Hänseler, 50 ml»', null, true),
  ('1302', 'Services de laboratoire médecine complémentaires', 'Laboratoire — Tous les services de laboratoire en médecine complémentaire sont enregistrés selon à la règle suivante:
"Numéro RCC ou nom et adresse du laboratoire, matériel d''origine, essais effectués"
Par exemple, "RCC No. XY, fèces, transglutaminase AC.""', null, true),
  ('1257', 'Coordination du traitement avec d''autres professionnels de la santé, par période de 5 min.', 'Naturopathe avec diplôme fédéral — S''applique aux rencontres personnelles ou téléphoniques entre des fournisseurs de services indépendants et des professionnels de santé (médecins, thérapeutes, services Spitex) en l''absence du patient. Ne s''applique pas à l''étude des dossiers ou aux réunions dans le cadre de la préparation des rapports.', null, true),
  ('1208', 'Traitement médicamenteux, par période de 5 min.', 'Naturopathe discipline Médecine ayurvédique — Thérapie médicamenteuse de la médecine complémentaire (thérapie, ordonnance, sélection, évaluation téléphonique), comme la phytothérapie, l''homéopathie fonctionnelle, les fleurs de Bach, la spagyrie, la biochimie selon Schüssler, etc. (médicament facturé séparément).', null, true),
  ('1212', 'Thérapie de l''ordre, par période de 5 min.', 'Naturopathe discipline Médecine ayurvédique — Contient des procédures et des mesures de l''ordre de vie basées sur la spécialité respective (par exemple, médecine humorale ou enseignement des 5 éléments).', null, true),
  ('1213', 'Technique de massage, par période de 5 min.', 'Naturopathe discipline Médecine naturelle traditionnelle européenne MTE — Comprend le massage du tissu conjonctif, le massage du côlon, le massage classique, le massage des points trigger', null, true),
  ('1215', 'Ayurvéda thérapie, par période de 5 min.', 'Méthode TC Ayurvéda thérapie', null, true),
  ('1216', 'Thérapie corporelle par le mouvement, par période de 5 min.', 'Méthode TC Thérapie corporelle par le mouvement', null, true),
  ('1221', 'Travail corporel aquatique, par période de 5min.', 'Méthode TC Travail corporel aquatique', null, true),
  ('1217', 'Art-therapie, par période de 5 min.', 'Art-thérapeute avec diplôme fédéral', null, true)
) as v(code, designation, description, unit, is_active)
on conflict (catalog_id, code) do update
  set designation = excluded.designation,
      description = excluded.description,
      is_active = true;
