// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';
import { getHoliswissAuthSpace, getHoliswissAuthStorageKey, type HoliswissAuthSpace } from './auth-space';

function createSupabaseClient(space: HoliswissAuthSpace) {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      storageKey: getHoliswissAuthStorageKey(space),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

const clients = new Map<HoliswissAuthSpace, ReturnType<typeof createSupabaseClient>>();

function getSupabaseClient() {
  const space = getHoliswissAuthSpace();
  let client = clients.get(space);
  if (!client) {
    client = createSupabaseClient(space);
    clients.set(space, client);
  }
  return client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    return Reflect.get(getSupabaseClient(), prop, receiver);
  },
});

// Oublie localement la session d'un espace (mémoire + storage) sans révoquer
// les tokens côté serveur. Indispensable après migration d'une session vers un
// autre espace : sinon deux clients gardent le même refresh token et leurs
// auto-refresh concurrents déclenchent la détection de réutilisation Supabase
// (rotation), ce qui révoque la session et déconnecte l'utilisateur.
export async function forgetAuthSpaceSession(space: HoliswissAuthSpace) {
  const client = clients.get(space);
  if (!client) return;
  try {
    await client.auth.signOut({ scope: "local" });
  } catch {
    // Le nettoyage du storage par l'appelant reste la garantie de dernier recours.
  }
}

export async function forgetAllAuthSpaceSessions(except?: HoliswissAuthSpace) {
  for (const space of clients.keys()) {
    if (space === except) continue;
    await forgetAuthSpaceSession(space);
  }
}

